version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    - image: circleci/postgres:9.6.2-alpine

    working_directory: ~/event-boardz-api

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: gradle dependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run: ./gradlew test
    - run: ./gradlew clean build
    - store_artifacts:
        path: build/libs/event-boardz-api-1.0-SNAPSHOT.jar

